language: php
sudo: false
php:
  - "7.1"
env:
  global:
    - CC_TEST_REPORTER_ID=7dca2dc3683851a1dcc3ec225f20fbd6ad95ad270f3ce511c5f3cf70e4c796bf
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - composer install
  - composer dump-autoload -o
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
